title: Mercy Eme # your name (or website title) here
logo: "images/IMG_3570.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  a data nerd with a creative flair, i'm your girl! 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn </a>
  <a href="https://mercysjournal.medium.com/">Medium Blog </a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
